#!venv/bin/python
# uses: openai 1.10.0, colorama 0.4.6

# import modules
from modules.openai import chat_completion
from colorama import Fore, Style
import argparse
import platform
import time

# define the request parameters
SYSTEM_PROMPT = f"Concisely execute the grokked user instruction. Environment: {platform.system()} {platform.release()}"
MAX_TOKENS = 200
TEMPERATURE = 0
MODEL = "gpt-3.5-turbo"

# main entry point to script
if __name__ == "__main__":
    # setup argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("prompt", type=str)
    args = parser.parse_args()

    # generate a completion from the user input
    response = chat_completion(
        _system_prompt=SYSTEM_PROMPT, 
        _user_prompt=args.prompt,
        _max_tokens=MAX_TOKENS,
        _temperature=TEMPERATURE,
        _model=MODEL)

    reply = response["content"]

    # print output to console
    print(f"🤖 {Fore.CYAN}", end="")
    for char in reply:
        print(char, end="", flush=True)
        time.sleep(0.005)
    print(f"{Style.RESET_ALL}")