#!/home/mishi/.config/openai/venv/bin/python
# uses: openai 1.10.0, rofi

# import modules
from modules.openai import chat_completion
import subprocess

# define the request parameters
SYSTEM_PROMPT = "Be concise and friendly."
MAX_TOKENS = 200
TEMPERATURE = 1
MODEL = "gpt-3.5-turbo"


# function to run rofi
def rofi_run():
    rofi_command = ['rofi', '-dmenu', '-p', '🤖', '-theme', '~/.config/rofi/themes/rofi-gpt']
    result = subprocess.run(rofi_command, capture_output=True, text=True).stdout.strip()
    return result


# main entry point to script
if __name__ == "__main__":
    user_prompt = rofi_run()
    if not user_prompt:
        print("User canceled. Exiting.")
    else:
        print(f"-> {user_prompt}")
        response = chat_completion(
            _system_prompt=SYSTEM_PROMPT,
            _user_prompt=user_prompt,
            _max_tokens=MAX_TOKENS,
            _temperature=TEMPERATURE,
            _model=MODEL)
        reply = response["content"]
        print(f"<- {reply}")
        dunstify_command = ['dunstify', reply, '-a', 'rofi-gpt']
        subprocess.run(dunstify_command)
